module.exports = {
  CHANGE_TIME: 'CHANGE_TIME',
  CHANGE_BPM: 'CHANGE_BPM',
  PLAY_DRUMKIT: 'PLAY_DRUMKIT',
  LOAD_DRUMKIT: 'LOAD_DRUMKIT',
  CHANGE_BIT: 'CHANGE_BIT',
  SET_CURRENTTIME: 'SET_CURRENTTIME',
  CHANGE_PAUSEDTIME: 'CHANGE_PAUSEDTIME',
  STOP_DRUMKIT: 'STOP_DRUMKIT',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  BIT_PUSHED: 'BIT_PUSHED',
  CHANGE_DPB:'CHANGE_DPB',
  CHANGE_BEATPEARMEASURE: 'CHANGE_BEATPEARMEASURE'
};
